<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="Shared.props" />

  <PropertyGroup>
    <AssemblyName>7Bpencil.BrighterInteriors</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony" />
    <Reference Include="spt-reflection" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BepInEx" />
    <Reference Include="UnityEngine" />
    <Reference Include="UnityEngine.CoreModule" />
  </ItemGroup>

</Project>
